PERGAMINHOS = {
    "Destreza": 4,
    "Combatividade": 5,
    "Maestria": 6,
    "Perseverança": 6,
    "Fortaleza": 6,
    "Arcane Mastery": 6,
    "Detonação": 6,
    "Pele de Pedra": 6,
    "Empalamento": 6,
    "Explosão Ninjutsu": 6,
    "Escudo de Ninjutsu": 6,
    "Jutsu de Cura": 6,
    "Golpe Fatal": 6,
    "Ataque Fatal": 6,
    "Função Ninja": 6,
    "Agressão Física": 6,
    "Benção de Defesa": 6,
    "Proteção Ninja": 6,
    "Jutsu Secreto Mortal": 6,
    "Ataque Rompedor": 6,
    "Brilho de Vitalidade": 6,
    "Abundância de Energia": 6,
    "Força Destruidora": 6,
    "Jutsu de Controle": 6,
    "Guarda Forte": 6,
    "Golpe em Cadeia": 6,
    "Golpe Fatal 2": 6,
    "Invulnerabilidade": 6,
    "Força da Fúria": 6,
    "Prosperidade": 6,
    "Meteoros de Fogo Voador": 6,
    "Ruptura Penetrante": 6,
    "Proteção Contra Dano": 6,
    "Defesa Firme": 6,
    "Acertos Consecutivos": 6,
    "Técnica do Acorrentamento": 6,
    "Redução de Dano": 6,
    "Golpes Consecutivos": 6
}
